spring.application.name=musically
spring.datasource.url=jdbc:mysql://localhost:3306/musicaly?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=rootpass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
jwt.secret=kKzA2GgKv1G5eUtR9Fq4WxqvEXo7j7iFktF/RHZRJJM=
